# Generated by Django 4.2.7 on 2023-11-14 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
