# Generated by Django 4.2.7 on 2023-11-20 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winned_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
