# Generated by Django 4.2.7 on 2023-11-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_listings_winner_delete_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
